os: linux
dist: xenial
language: generic

env:
  global:
    - "GIT_REPO_SLUG=dullage/tahskr-server"
    - "DOCKER_REPO_SLUG=dullage/tahskr-server"
    - "VERSION_BUMP_MESSAGE_PREFIX='Travis CI: Bump version to'"
# secret:
#   - DOCKER_USERNAME
#   - DOCKER_PASSWORD
#   - GITHUB_TOKEN
#   - encrypted_7df0bf92a043_iv
#   - encrypted_7df0bf92a043_key
#   - DEPLOY_SCRIPT_DEV
#   - DEPLOY_SCRIPT_PROD
#   - DEPLOY_HOST_IP

services:
  - docker

install:
  - sudo apt update
  - sudo apt -y install jq

if: tag IS NOT present

stages:
  - name: Test Build
    if: commit_message !~ env(VERSION_BUMP_MESSAGE_PREFIX)

  - name: Bump Version
    if: branch = master && type = push && commit_message !~ env(VERSION_BUMP_MESSAGE_PREFIX)

  - name: Build and Push
    if: branch = master && type = push && commit_message =~ env(VERSION_BUMP_MESSAGE_PREFIX)

  - name: Crete Manifest and Push
    if: branch = master && type = push && commit_message =~ env(VERSION_BUMP_MESSAGE_PREFIX)

  - name: Deploy Prod
    if: branch = master && type = push && commit_message =~ env(VERSION_BUMP_MESSAGE_PREFIX)

  - name: Deploy Dev
    if: branch = develop && type = push

jobs:
  include:
    - stage: Test Build
      arch: amd64
      script: bash ./.travis/build.sh amd64
    - arch: arm64
      script: bash ./.travis/build.sh arm64

    - stage: Bump Version
      arch: amd64
      script: bash ./.travis/bump_version.sh

    - stage: Build and Push
      arch: amd64
      script: bash ./.travis/build.sh amd64 push
    - arch: arm64
      script: bash ./.travis/build.sh arm64 push

    - stage: Crete Manifest and Push
      arch: amd64
      script: bash ./.travis/manifest.sh

    - stage: Deploy Prod
      arch: amd64
      install: skip
      script: bash ./.travis/deploy.sh prod

    - stage: Deploy Dev
      arch: amd64
      install: skip
      script: bash ./.travis/deploy.sh dev
